server:
  port: 8100
mybatis-plus:
  type-aliases-package: com.bcs.study.module.*.*.domain
  mapper-locations: classpath:/mapper/**/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/study?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://server.natappfree.cc:45034/study?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1124
  thymeleaf:
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML
    enabled: true
    servlet:
      content-type: text/html
  freemarker:
    template-loader-path: classpath:/templates/freemarker/
    cache: false
springdoc:
